=== xstudentnci/FDA-net/WAD-CA1/bin/Debug/netcoreapp3.1/ProductsSchema.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- definition of simple elements -->
	<xs:element name="category" type="xs:string"/>
	<xs:element name="name" type="xs:string"/>
	<xs:element name="description" type="xs:string"/>
	<xs:element name="quantity">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="unitprice">
		<xs:simpleType >
			<xs:restriction base="xs:decimal">
				<xs:minInclusive value="0"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:attribute name="code">
		<xs:simpleType>
			<xs:restriction base="xs:token">
				<xs:pattern value="[0-9][0-9][0-9]-[0-9][0-9]"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:attribute>
	
	<!-- definition of attributes -->
	<!--<xs:attribute ref="xs:code" use="required"/>-->
	
	<!-- definition of complex elements -->
	<xs:element name="product">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="category"/>
				<xs:element ref="name"/>
				<xs:element ref="description"/>
				<xs:element ref="quantity"/>
				<xs:element ref="unitprice"/>
			</xs:sequence>
			<xs:attribute ref="code" use="required"/>
		</xs:complexType>
	</xs:element>

	<xs:element name="products">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="product" minOccurs="10" maxOccurs="unbounded"/>				
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== xstudentnci/FDA-net/XmlFiles/WithErrors/Products-3ErrorsOnQuantity.xml
<?xml version="1.0" encoding="utf-8" ?>
<products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation='productsSchema.xsd'>	
	<product code="123-00">
		<category>CategoryA</category>
		<name>Product A</name>
		<description>Description A</description>
		<quantity>abc</quantity>
		<unitprice>10.50</unitprice>
	</product>
	<product code="123-01">
		<category>CategoryA</category>
		<name>Product B</name>
		<description>Description B</description>
		<quantity>5</quantity>
		<unitprice>5.0</unitprice>
	</product>
	<product code="123-02">
		<category>CategoryB</category>
		<name>Product C</name>
		<description>Description C</description>
		<quantity>100</quantity>
		<unitprice>7</unitprice>
	</product>
	<product code="123-03">
		<category>CategoryC</category>
		<name>Product D</name>
		<description>Description D</description>
		<quantity>abc</quantity>
		<unitprice>10.50</unitprice>
	</product>
	<product code="123-04">
		<category>CategoryA</category>
		<name>Product E</name>
		<description>Description E</description>
		<quantity>5</quantity>
		<unitprice>5.0</unitprice>
	</product>
	<product code="123-05">
		<category>CategoryB</category>
		<name>Product F</name>
		<description>Description F</description>
		<quantity>100</quantity>
		<unitprice>7</unitprice>
	</product>
	<product code="123-06">
		<category>CategoryC</category>
		<name>Product D</name>
		<description>Description D</description>
		<quantity>50</quantity>
		<unitprice>10.50</unitprice>
	</product>
	<product code="123-07">
		<category>CategoryA</category>
		<name>Product E</name>
		<description>Description E</description>
		<quantity>5</quantity>
		<unitprice>5.0</unitprice>
	</product>
	<product code="123-08">
		<category>CategoryB</category>
		<name>Product F</name>
		<description>Description F</description>
		<quantity>-1</quantity>
		<unitprice>7</unitprice>
	</product>
	<product code="123-09">
		<category>CategoryB</category>
		<name>Product F</name>
		<description>Description F</description>
		<quantity>100</quantity>
		<unitprice>7</unitprice>
	</product>
</products>

=== xstudentnci/FDA-net/XmlFiles/Valid/Products-15 products.xml
<?xml version="1.0" encoding="utf-8" ?>
<products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation='productsSchema.xsd'>	
	<product code="888-00">
		<category>CategoryA</category>
		<name>Product 00</name>
		<description>Description 00</description>
		<quantity>50</quantity>
		<unitprice>10.50</unitprice>
	</product>
	<product code="888-01">
		<category>CategoryA</category>
		<name>Product 01</name>
		<description>Description 01</description>
		<quantity>5</quantity>
		<unitprice>5.0</unitprice>
	</product>
	<product code="888-02">
		<category>CategoryB</category>
		<name>Product 02</name>
		<description>Description 02</description>
		<quantity>100</quantity>
		<unitprice>7</unitprice>
	</product>
	<product code="888-03">
		<category>CategoryC</category>
		<name>Product 03</name>
		<description>Description 03</description>
		<quantity>50</quantity>
		<unitprice>10.50</unitprice>
	</product>
	<product code="888-04">
		<category>CategoryA</category>
		<name>Product 04</name>
		<description>Description 04</description>
		<quantity>5</quantity>
		<unitprice>5.0</unitprice>
	</product>
	<product code="888-05">
		<category>CategoryB</category>
		<name>Product 05</name>
		<description>Description 05</description>
		<quantity>100</quantity>
		<unitprice>7</unitprice>
	</product>
	<product code="888-06">
		<category>CategoryC</category>
		<name>Product 06</name>
		<description>Description 06</description>
		<quantity>50</quantity>
		<unitprice>10.50</unitprice>
	</product>
	<product code="888-07">
		<category>CategoryA</category>
		<name>Product 07</name>
		<description>Description 07</description>
		<quantity>5</quantity>
		<unitprice>5.0</unitprice>
	</product>
	<product code="888-08">
		<category>CategoryB</category>
		<name>Product 08</name>
		<description>Description 08</description>
		<quantity>100</quantity>
		<unitprice>7</unitprice>
	</product>
	<product code="888-09">
		<category>CategoryB</category>
		<name>Product 09</name>
		<description>Description 09</description>
		<quantity>100</quantity>
		<unitprice>7</unitprice>
	</product>	
	<product code="888-10">
		<category>CategoryB</category>
		<name>Product 10</name>
		<description>Description 10</description>
		<quantity>100</quantity>
		<unitprice>7</unitprice>
	</product>
	<product code="888-11">
		<category>CategoryB</category>
		<name>Product 11</name>
		<description>Description 11</description>
		<quantity>100</quantity>
		<unitprice>7</unitprice>
	</product>
	<product code="888-12">
		<category>CategoryB</category>
		<name>Product 12</name>
		<description>Description 12</description>
		<quantity>100</quantity>
		<unitprice>7</unitprice>
	</product>
	<product code="888-13">
		<category>CategoryB</category>
		<name>Product 13"</name>
		<description>Description 13"</description>
		<quantity>100</quantity>
		<unitprice>7</unitprice>
	</product>
	<product code="888-14">
		<category>CategoryB</category>
		<name>Product 14</name>
		<description>Description 14</description>
		<quantity>67</quantity>
		<unitprice>87</unitprice>
	</product>
</products>

=== xstudentnci/FDA-net/XmlFiles/WithErrors/ProductsWith4Errors.xml
<?xml version="1.0" encoding="utf-8" ?>
<?xml-stylesheet type="text/xsl" href="ProductsTransformation.xsl" ?>
<products xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation='productsSchema.xsd'>
	
	<product code="888-01A">
		<category>CategoryA</category>
		<name>Product A</name>
		<description>Description A</description>
		<quantity>50</quantity>
		<unitprice>10.50</unitprice>
	</product>
	<product code="888A-02">
		<category>CategoryA</category>
		<name>Product B</name>
		<description>Description B</description>
		<quantity>5</quantity>
		<unitprice>5.0</unitprice>
	</product>
	<product code="888-02">
		<category>CategoryB</category>
		<name>Product C</name>
		<description>Description C</description>
		<quantity>abc</quantity>
		<unitprice>7</unitprice>
	</product>

	<product code="888-03">
		<category>CategoryC</category>
		<name>Product D</name>
		<description>Description D</description>
		<quantity>50</quantity>
		<unitprice>abc</unitprice>
	</product>
	<product code="888-04">
		<category>CategoryA</category>
		<name>Product E</name>
		<description>Description E</description>
		<quantity>5</quantity>
		<unitprice>5.0</unitprice>
	</product>
	<product code="888-05">
		<category>CategoryB</category>
		<name>Product F</name>
		<description>Description F</description>
		<quantity>100</quantity>
		<unitprice>7</unitprice>
	</product>

	<product code="888-06">
		<category>CategoryC</category>
		<name>Product D</name>
		<description>Description D</description>
		<quantity>50</quantity>
		<unitprice>10.50</unitprice>
	</product>
	<product code="888-07">
		<category>CategoryA</category>
		<name>Product E</name>
		<description>Description E</description>
		<quantity>5</quantity>
		<unitprice>5.0</unitprice>
	</product>
	<product code="888-08">
		<category>CategoryB</category>
		<name>Product F</name>
		<description>Description F</description>
		<quantity>100</quantity>
		<unitprice>7</unitprice>
	</product>

	<product code="888-09">
		<category>CategoryB</category>
		<name>Product F</name>
		<description>Description F</description>
		<quantity>100</quantity>
		<unitprice>7</unitprice>
	</product>

	<product code="888-10">
		<category>CategoryB</category>
		<name>Product F</name>
		<description>Description F</description>
		<quantity>100</quantity>
		<unitprice>7</unitprice>
	</product>
</products>
